// default package
// Generated 2016-10-22 23:18:20 by Hibernate Tools 5.1.0.Beta1
package com.kordian.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * RoleType generated by hbm2java
 */
public class RoleType implements java.io.Serializable {

	private Integer roleTypeId;
	private String role;
	private Set userRoles = new HashSet(0);

	public RoleType() {
	}

	public RoleType(String role) {
		this.role = role;
	}

	public RoleType(String role, Set userRoles) {
		this.role = role;
		this.userRoles = userRoles;
	}

	public Integer getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setRoleTypeId(Integer roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

}
