// default package
// Generated 2016-10-22 23:18:20 by Hibernate Tools 5.1.0.Beta1
package com.kordian.domain;

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private Integer userRoleId;
	private RoleType roleType;
	private User user;

	public UserRole() {
	}

	public UserRole(RoleType roleType, User user) {
		this.roleType = roleType;
		this.user = user;
	}

	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	public RoleType getRoleType() {
		return this.roleType;
	}

	public void setRoleType(RoleType roleType) {
		this.roleType = roleType;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
