// default package
// Generated 2016-10-22 23:18:20 by Hibernate Tools 5.1.0.Beta1
package com.kordian.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String name;
	private String surname;
	private String hashedPwd;
	private Set userRoles = new HashSet(0);

	public User() {
	}

	public User(String username, String name, String surname, String hashedPwd, Set userRoles) {
		this.username = username;
		this.name = name;
		this.surname = surname;
		this.hashedPwd = hashedPwd;
		this.userRoles = userRoles;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getHashedPwd() {
		return this.hashedPwd;
	}

	public void setHashedPwd(String hashedPwd) {
		this.hashedPwd = hashedPwd;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

}
